// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBwq7ozcKRvKPAWglBcfAdYO_Za-2nunCY',
    appId: '1:357946440833:web:c610f6fe80a914b5c4e180',
    messagingSenderId: '357946440833',
    projectId: 'ardapp-4bf3a',
    authDomain: 'ardapp-4bf3a.firebaseapp.com',
    storageBucket: 'ardapp-4bf3a.appspot.com',
    measurementId: 'G-V93PTG8DKL',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD-x29GD_gbpsrksQm9TI2k32xsP6NHmxw',
    appId: '1:357946440833:android:2b18577b212cc30bc4e180',
    messagingSenderId: '357946440833',
    projectId: 'ardapp-4bf3a',
    storageBucket: 'ardapp-4bf3a.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA2acvc9_mCyIRBHHUuQwoCssKXs-klhSA',
    appId: '1:357946440833:ios:4fb5f5b5a9794bb5c4e180',
    messagingSenderId: '357946440833',
    projectId: 'ardapp-4bf3a',
    storageBucket: 'ardapp-4bf3a.appspot.com',
    iosBundleId: 'com.example.noteapp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyA2acvc9_mCyIRBHHUuQwoCssKXs-klhSA',
    appId: '1:357946440833:ios:4fb5f5b5a9794bb5c4e180',
    messagingSenderId: '357946440833',
    projectId: 'ardapp-4bf3a',
    storageBucket: 'ardapp-4bf3a.appspot.com',
    iosBundleId: 'com.example.noteapp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBwq7ozcKRvKPAWglBcfAdYO_Za-2nunCY',
    appId: '1:357946440833:web:bf07ddcc9fe33248c4e180',
    messagingSenderId: '357946440833',
    projectId: 'ardapp-4bf3a',
    authDomain: 'ardapp-4bf3a.firebaseapp.com',
    storageBucket: 'ardapp-4bf3a.appspot.com',
    measurementId: 'G-QR8RJ3QN2W',
  );
}
